-- MySQL Script generated by MySQL Workbench
-- Tue Nov 23 15:27:58 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Werwolf
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Werwolf` ;

-- -----------------------------------------------------
-- Schema Werwolf
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Werwolf` DEFAULT CHARACTER SET utf8 ;
USE `Werwolf` ;

-- -----------------------------------------------------
-- Table `Werwolf`.`Rolle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Werwolf`.`Rolle` ;

CREATE TABLE IF NOT EXISTS `Werwolf`.`Rolle` (
  `idRolle` VARCHAR(45) NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Funktion` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idRolle`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Werwolf`.`Karte`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Werwolf`.`Karte` ;

CREATE TABLE IF NOT EXISTS `Werwolf`.`Karte` (
  `idKarte` VARCHAR(45) NOT NULL,
  `Bild` BLOB NULL,
  `Rolle_idRolle` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idKarte`, `Rolle_idRolle`),
  INDEX `fk_Karte_Rolle_idx` (`Rolle_idRolle` ASC) VISIBLE,
  CONSTRAINT `fk_Karte_Rolle`
    FOREIGN KEY (`Rolle_idRolle`)
    REFERENCES `Werwolf`.`Rolle` (`idRolle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Werwolf`.`Regeln`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Werwolf`.`Regeln` ;

CREATE TABLE IF NOT EXISTS `Werwolf`.`Regeln` (
  `idRegeln` VARCHAR(45) NOT NULL,
  `Regelname` VARCHAR(45) NULL,
  `Regelbeschreibung` VARCHAR(255) NULL,
  `Rolle_idRolle` VARCHAR(45) NULL,
  PRIMARY KEY (`idRegeln`, `Rolle_idRolle`),
  INDEX `fk_Regeln_Rolle1_idx` (`Rolle_idRolle` ASC) VISIBLE,
  UNIQUE INDEX `Rolle_idRolle_UNIQUE` (`Rolle_idRolle` ASC) VISIBLE,
  CONSTRAINT `fk_Regeln_Rolle1`
    FOREIGN KEY (`Rolle_idRolle`)
    REFERENCES `Werwolf`.`Rolle` (`idRolle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `Werwolf`.`Rolle`
-- -----------------------------------------------------
START TRANSACTION;
USE `Werwolf`;
INSERT INTO `Werwolf`.`Rolle` (`idRolle`, `Name`, `Funktion`) VALUES ('b0Wolf', 'Werwolf', 'Frisst nachts Dorfbewohner');

COMMIT;


-- -----------------------------------------------------
-- Data for table `Werwolf`.`Karte`
-- -----------------------------------------------------
START TRANSACTION;
USE `Werwolf`;
INSERT INTO `Werwolf`.`Karte` (`idKarte`, `Bild`, `Rolle_idRolle`) VALUES ('k_b0Wolf', NULL, 'b0Wolf');

COMMIT;


-- -----------------------------------------------------
-- Data for table `Werwolf`.`Regeln`
-- -----------------------------------------------------
START TRANSACTION;
USE `Werwolf`;
INSERT INTO `Werwolf`.`Regeln` (`idRegeln`, `Regelname`, `Regelbeschreibung`, `Rolle_idRolle`) VALUES ('k_0Wolf', 'Normaler Werwolf', 'Der normale Werwolf wacht jede Nacht auf und sucht sich gemeinsam mit den anderen Werwölfen ein Opfer aus. Das ausgewählte Opfer wacht (außer geschützt durch Sonderrollen) am nächsten Morgen nicht auf. Der Werwolf gewinnt gemeinsam mit den anderen Werwölfen wenn nur noch Werwölfe übrig sind.', 'b0Wolf');

COMMIT;

